apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sisyphus
  name: sisyphus
  namespace: sisyphus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sisyphus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sisyphus
    spec:
      containers:
      - image: ugurozturk99/sisyphus:latest
        imagePullPolicy: Always
        name: sisyphus
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 64Mi
        volumeMounts:
        - mountPath: /workspace
          name: workspace
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: sisyphus-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sisyphus-pvc
  namespace: sisyphus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sisyphus
  name: sisyphus-svc
  namespace: sisyphus
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http
  selector:
    app: sisyphus
  sessionAffinity: None
  type: NodePort