apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: CA
    server: IP
  name: CLUSTERNAME
contexts:
- context:
    cluster: CLUSTERNAME
    user: USER
  name: USER-CLUSTERNAME
current-context: USER-CLUSTERNAME
kind: Config
preferences: {}
users:
- name: USER
  user:
    client-certificate-data: CERT
    client-key-data: KEY
