apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${CI_PROJECT_NAME}
  name: ${CI_PROJECT_NAME} 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ${CI_PROJECT_NAME} 
  strategy: {}
  template:
    metadata:
      labels:
        app: ${CI_PROJECT_NAME} 
    spec:
      containers:
      - image: ugurozturk99/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
        name: ${CI_PROJECT_NAME}
        volumeMounts:
        - mountPath: "/workspace"
          name: workspace
        ports:
        - containerPort: 5000
          name: http-${CI_PROJECT_NAME}
          protocol: TCP
        resources:
          requests:
             memory: "64Mi"
             cpu: "20m"
          limits:
             memory: "128Mi"
             cpu: "500m"
      - name: nginx
        image: nginx:stable
        resources:
          requests:
             memory: "64Mi"
             cpu: "20m"
          limits:
             memory: "128Mi"
             cpu: "500m"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: ${CI_PROJECT_NAME}-pvc
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
