apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${CI_PROJECT_NAME} 
  name: ${CI_PROJECT_NAME}-svc 
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: ${CI_PROJECT_NAME} 
  type: NodePort
